query {
  post(id: 860) {
    __typename
    ... on Post {
      id
      title
    }
    ... on PostError {
      statusCode
      message
      ... on PostNotFoundError {
        postId
      }
      ... on PostNotFoundId {
        info
      }
    }
  }
}
