fragment userFragment on User {
  id
  firstName
  lastName
  userName
  indexRef
  createdAt
}

fragment postFragment on Post {
  id
  title
  body
  indexRef
  createdAt
}

query GetUser {
  user(id: 903) {
    ...userFragment
  }
}

query GetUsers {
  users {
    ...userFragment
  }
}

query GetPost {
  post(id: 860) {
    ...postFragment
  }
}

query GetPosts {
  posts {
    ...postFragment
  }
}
