query GetUser {
  user {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
  }
}

query GetUsers {
  users {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
  }
}
